[package]
name = "mao_core"
version = "0.1.0"
edition = "2021"
description = "A core library for playing to the mao board game, with the handle of custom rules !"
license-file = "LICENSE"


[dependencies]
anyhow = "1.0.83"
libloading = "0.8"
rand = "0.8.5"
